[package]
name = "maglev-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.105"
quote = "1.0.43"
syn = { version = "2.0.114", features = ["full"] }

[dev-dependencies]
http = "1.4.0"
anyhow = "1.0.100"
thiserror = "2.0.17"
