[package]
name = "maglev-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "maglev"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.100"
askama = "0.13.1"
clap = { version = "4.5.54", features = ["derive"] }
heck = "0.5.0"
pluralizer = "0.5.0"
log = "0.4.29"
simplelog = "0.12.2"


